default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: neosoft
  password: ac3r 

development:
  <<: *default
  database: shopify_rest_api_development

test:
  <<: *default
  database: shopify_rest_api_test

production:
  <<: *default
  database: shopify_rest_api_production
